export interface ConnectorPreset {
  id: string; // also seeds the connection id; MUST match /^[a-z0-9][a-z0-9-]{0,63}$/
  name: string;
  category: 'project' | 'dev' | 'data' | 'search' | 'docs' | 'business';
  accent: string; // hex color for the monogram chip, e.g. '#5E6AD2'
  url: string;
  transport: 'streamable-http';
  auth:
    | { kind: 'none' }
    | { kind: 'bearer'; placeholder: string }
    | { kind: 'header'; headerName: string; valuePrefix?: string; placeholder: string };
  tokenDocsUrl?: string;
  tokenDocsHint?: string;
  notes?: string;
}

export const CONNECTOR_PRESETS: ConnectorPreset[] = [
  {
    id: 'linear',
    name: 'Linear',
    category: 'project',
    accent: '#5E6AD2',
    url: 'https://mcp.linear.app/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'lin_api_…' },
    tokenDocsUrl: 'https://linear.app/docs/mcp',
    tokenDocsHint: 'Linear → Settings → Account → Security & Access → Personal API keys',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'dev',
    accent: '#362D59',
    url: 'https://mcp.sentry.dev/mcp',
    transport: 'streamable-http',
    auth: {
      kind: 'header',
      headerName: 'Authorization',
      valuePrefix: 'Sentry-Bearer ',
      placeholder: 'User Auth Token',
    },
    tokenDocsUrl: 'https://sentry.io/settings/account/api/auth-tokens/',
    tokenDocsHint: 'Sentry → Settings → Account → User Auth Tokens',
    notes: 'Uses a non-standard Sentry-Bearer authorization scheme.',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'business',
    accent: '#635BFF',
    url: 'https://mcp.stripe.com',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'rk_live_…' },
    tokenDocsUrl: 'https://dashboard.stripe.com/apikeys',
    tokenDocsHint: 'Stripe → Developers → API keys',
    notes: 'Use a restricted key (rk_), not a full secret key.',
  },
  {
    id: 'cloudflare-docs',
    name: 'Cloudflare Docs',
    category: 'dev',
    accent: '#F38020',
    url: 'https://docs.mcp.cloudflare.com/mcp',
    transport: 'streamable-http',
    auth: { kind: 'none' },
    notes: 'No token needed.',
  },
  {
    id: 'cloudflare-bindings',
    name: 'Cloudflare Bindings',
    category: 'dev',
    accent: '#F38020',
    url: 'https://bindings.mcp.cloudflare.com/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'Cloudflare API token' },
    tokenDocsUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    tokenDocsHint: 'Cloudflare → My Profile → API Tokens',
  },
  {
    id: 'cloudflare-observability',
    name: 'Cloudflare Observability',
    category: 'dev',
    accent: '#F38020',
    url: 'https://observability.mcp.cloudflare.com/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'Cloudflare API token' },
    tokenDocsUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    tokenDocsHint: 'Cloudflare → My Profile → API Tokens',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'data',
    accent: '#3ECF8E',
    url: 'https://mcp.supabase.com/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'sbp_…' },
    tokenDocsUrl: 'https://supabase.com/dashboard/account/tokens',
    tokenDocsHint: 'Supabase → Account → Access Tokens',
    notes: 'Append ?read_only=true to the URL (Advanced) to limit to reads.',
  },
  {
    id: 'neon',
    name: 'Neon',
    category: 'data',
    accent: '#00E599',
    url: 'https://mcp.neon.tech/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'Neon API key' },
    tokenDocsUrl: 'https://console.neon.tech/app/settings/api-keys',
    tokenDocsHint: 'Neon → Account settings → API keys',
  },
  {
    id: 'posthog',
    name: 'PostHog',
    category: 'data',
    accent: '#F54E00',
    url: 'https://mcp.posthog.com/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'phx_…' },
    tokenDocsUrl: 'https://us.posthog.com/settings/user-api-keys',
    tokenDocsHint: 'PostHog → Settings → Personal API keys',
    notes: 'EU cloud: use https://mcp-eu.posthog.com/mcp (Advanced).',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'data',
    accent: '#18BFFF',
    url: 'https://mcp.airtable.com/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'pat…' },
    tokenDocsUrl: 'https://airtable.com/create/tokens',
    tokenDocsHint: 'Airtable → Builder hub → Personal access tokens',
  },
  {
    id: 'monday',
    name: 'Monday.com',
    category: 'project',
    accent: '#FF3D57',
    url: 'https://mcp.monday.com/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'monday.com API token' },
    tokenDocsUrl: 'https://developer.monday.com/api-reference/docs/authentication',
    tokenDocsHint: 'monday.com → avatar → Developers → My access tokens',
  },
  {
    id: 'intercom',
    name: 'Intercom',
    category: 'business',
    accent: '#1F8DED',
    url: 'https://mcp.intercom.com/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'Intercom access token' },
    tokenDocsUrl:
      'https://developers.intercom.com/docs/build-an-integration/learn-more/authentication',
    tokenDocsHint: 'Intercom → Settings → Developers',
    notes: 'US-hosted workspaces only.',
  },
  {
    id: 'exa',
    name: 'Exa',
    category: 'search',
    accent: '#1F40FF',
    url: 'https://mcp.exa.ai/mcp',
    transport: 'streamable-http',
    auth: { kind: 'header', headerName: 'x-api-key', placeholder: 'Exa API key' },
    tokenDocsUrl: 'https://dashboard.exa.ai/api-keys',
    tokenDocsHint: 'Exa → Dashboard → API keys',
    notes: 'Also works without a key at lower limits.',
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    category: 'search',
    accent: '#FF5A1F',
    url: 'https://mcp.firecrawl.dev/v2/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'fc-…' },
    tokenDocsUrl: 'https://www.firecrawl.dev/app/api-keys',
    tokenDocsHint: 'Firecrawl → Dashboard → API keys',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'data',
    accent: '#FFD21E',
    url: 'https://huggingface.co/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'hf_…' },
    tokenDocsUrl: 'https://huggingface.co/settings/tokens',
    tokenDocsHint: 'Hugging Face → Settings → Access Tokens (read scope)',
  },
  {
    id: 'ahrefs',
    name: 'Ahrefs',
    category: 'search',
    accent: '#FF8D00',
    url: 'https://api.ahrefs.com/mcp/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'Ahrefs MCP key' },
    tokenDocsUrl: 'https://docs.ahrefs.com/docs/mcp/reference/introduction',
    tokenDocsHint: 'Ahrefs → Account settings → API keys → Generate MCP key',
    notes: 'Lite plan or higher. Use a dedicated MCP key — regular API keys are not accepted.',
  },
  {
    id: 'fireflies',
    name: 'Fireflies',
    category: 'business',
    accent: '#E1447E',
    url: 'https://api.fireflies.ai/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'Fireflies API key' },
    tokenDocsUrl: 'https://docs.fireflies.ai/getting-started/mcp-configuration',
    tokenDocsHint: 'Fireflies → Settings → Developer settings → API key',
  },
  {
    id: 'gamma',
    name: 'Gamma',
    category: 'docs',
    accent: '#3B5BDB',
    url: 'https://mcp.gamma.app/mcp',
    transport: 'streamable-http',
    auth: { kind: 'header', headerName: 'X-API-KEY', placeholder: 'sk-gamma-…' },
    tokenDocsUrl: 'https://gamma.app/settings/api-keys',
    tokenDocsHint: 'Gamma → Settings → API keys',
    notes: 'API keys require a Pro, Ultra, Teams, or Business plan.',
  },
  {
    id: 'incident-io',
    name: 'incident.io',
    category: 'dev',
    accent: '#F25533',
    url: 'https://mcp.incident.io/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'incident.io API key' },
    tokenDocsUrl: 'https://docs.incident.io/ai/remote-mcp',
    tokenDocsHint: 'incident.io → Settings → API keys',
    notes: 'Public beta — Team, Pro, and Enterprise plans.',
  },
  {
    id: 'lunarcrush',
    name: 'LunarCrush',
    category: 'data',
    accent: '#101113',
    url: 'https://lunarcrush.ai/mcp',
    transport: 'streamable-http',
    auth: { kind: 'bearer', placeholder: 'LunarCrush API key' },
    tokenDocsUrl: 'https://lunarcrush.com/developers/api/authentication',
    tokenDocsHint: 'LunarCrush → Developers → API authentication',
    notes: 'API key requires a LunarCrush subscription.',
  },
];

export function getConnectorPreset(id: string): ConnectorPreset | undefined {
  return CONNECTOR_PRESETS.find((preset) => preset.id === id);
}
